apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort # Allows external access via a static port on each node
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 31601 # You can choose any available port between 30000-32767
      name: http
