apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - elasticsearch/es-pvc.yaml
  
  - elasticsearch/service.yaml
  - kibana/service.yaml
  - fleet/service.yaml

  - elasticsearch/elasticsearch.yml
  - kibana/kibana.yml
  - fleet/fleet.yml
  
  - elasticsearch/deployment.yaml
  - kibana/deployment.yaml
  - fleet/deployment.yaml
