apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - elasticsearch/service.yaml
  - kibana/service.yaml
  - fleet/service.yaml

  - elasticsearch/deployment.yaml
  - kibana/deployment.yaml
  - fleet/deployment.yaml
