# Generated by Django 5.2.7 on 2025-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='enterprise_description',
            field=models.CharField(blank=True, default='Dedicated support and infrastructure for your company.', max_length=255),
        ),
        migrations.AddField(
            model_name='pricing',
            name='enterprise_price',
            field=models.DecimalField(decimal_places=2, default=99.0, help_text='Price for the Enterprise plan', max_digits=6),
        ),
        migrations.AddField(
            model_name='pricing',
            name='hobby_description',
            field=models.CharField(blank=True, default="The perfect plan if you're just getting started.", max_length=255),
        ),
        migrations.AddField(
            model_name='pricing',
            name='hobby_price',
            field=models.DecimalField(decimal_places=2, default=29.0, help_text='Price for the Hobby plan', max_digits=6),
        ),
    ]
