# Generated by Django 5.2.7 on 2025-10-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricing_enterprise_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='body',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='enterprise_description',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='enterprise_price',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='hobby_description',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='hobby_price',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='intro',
        ),
        migrations.AddField(
            model_name='pricing',
            name='premium_features',
            field=models.TextField(blank=True, default='Everything in Standard plus: access to the SOC environment and Elastic environment for AI learning product selling.', help_text='Extra features for Premium plan'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='Base cost per month (€)', max_digits=6),
        ),
        migrations.AddField(
            model_name='pricing',
            name='standard_device_cost',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Cost per device per month (€)', max_digits=6),
        ),
        migrations.AddField(
            model_name='pricing',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Base cost per month (€)', max_digits=6),
        ),
        migrations.AddField(
            model_name='pricing',
            name='standard_support',
            field=models.CharField(default='24-hour support', help_text='Support details for Standard plan', max_length=255),
        ),
    ]
