# Generated by Django 5.2.7 on 2025-10-31 15:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_remove_pricing_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='standard_support',
        ),
        migrations.AddField(
            model_name='pricing',
            name='standard_features',
            field=wagtail.fields.StreamField([('feature', 0)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Feature'})}, default=[{'type': 'feature', 'value': 'Real-time antivirus and malware protection'}, {'type': 'feature', 'value': 'Behavioral threat detection'}, {'type': 'feature', 'value': 'Centralized agent management'}, {'type': 'feature', 'value': 'Endpoint telemetry collection'}, {'type': 'feature', 'value': 'Machine learning–based anomaly detection'}, {'type': 'feature', 'value': 'Attack surface reduction'}, {'type': 'feature', 'value': 'Integration with Elastic Security SIEM'}, {'type': 'feature', 'value': '24-hour support'}], help_text='List of Standard plan features'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='premium_features',
            field=wagtail.fields.StreamField([('feature', 0)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Feature'})}, default=[{'type': 'feature', 'value': 'Everything in Standard, plus:'}, {'type': 'feature', 'value': 'Access to SOC environment'}, {'type': 'feature', 'value': 'AI-powered threat detection (Elastic ML)'}, {'type': 'feature', 'value': 'Automated case management and response'}, {'type': 'feature', 'value': 'Threat hunting dashboards and correlation views'}, {'type': 'feature', 'value': 'Integration with Holm Security & Microsoft Defender'}, {'type': 'feature', 'value': 'Elastic AI Assistant and AI learning access'}, {'type': 'feature', 'value': 'Full Elastic Stack access for visualization and analysis'}], help_text='List of Premium plan features'),
        ),
    ]
