# Generated by Django 5.2.7 on 2025-10-31 15:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_pricing_premium_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='premium_features',
            field=wagtail.fields.StreamField([('feature', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Feature'})}, default=None, help_text='List of Premium plan features', null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='standard_features',
            field=wagtail.fields.StreamField([('feature', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Feature'})}, default=None, help_text='List of Standard plan features', null=True),
        ),
    ]
