apiVersion: apps/v1
kind: Deployment
metadata:
  name: wagtail
  labels:
    app: wagtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wagtail
  template:
    metadata:
      labels:
        app: wagtail
    spec:
      containers:
        - name: wagtail
          image: kickb1/wagtail-site:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # Database Configuration
            - name: POSTGRES_DB
              value: wagtaildb
            - name: POSTGRES_USER
              value: wagtailuser
            - name: POSTGRES_PASSWORD
              value: supersecret
            - name: DJANGO_SETTINGS_MODULE
              value: mysite.settings.dev
          volumeMounts:
            # Mount 1: Media directory
            - name: wagtail-data-volume  # <-- Uses the single volume definition
              mountPath: /vol/web/media
            # Mount 2: Static files directory
            - name: wagtail-data-volume  # <-- Uses the single volume definition
              mountPath: /vol/web/static
      volumes:
        # Define the single volume that claims the PVC
        - name: wagtail-data-volume  # <-- Single volume name
          persistentVolumeClaim:
            claimName: wagtail-pvc