apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-server-config
data:
  fleet.yml: |
    server:
      host: "0.0.0.0"
      port: 8220

    elasticsearch:
      hosts: ["https://elasticsearch:9200"]
      ssl:
        certificateAuthorities: ["/usr/share/fleet-server/config/certs/ca.crt"]
        verificationMode: certificate
      serviceAccountToken: ${ELASTICSEARCH_SERVICE_TOKEN}

    # Monitoring (optional)
    monitoring:
      enabled: true
      elasticsearch:
        hosts: ["https://elasticsearch:9200"]
        ssl:
          certificateAuthorities: ["/usr/share/fleet-server/config/certs/ca.crt"]
          verificationMode: certificate
