# Generated by Django 5.2.3 on 2025-06-14 14:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_writeuppage_writeupsindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text for the homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle for the homepage', max_length=255),
        ),
        migrations.AlterField(
            model_name='writeuppage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('code', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text for the heading', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')], 'help_text': 'Size of the heading'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 6: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {'label': 'Code'})}),
        ),
        migrations.DeleteModel(
            name='WriteupsIndexPage',
        ),
    ]
