# Generated by Django 5.2.3 on 2025-06-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_writeupitempage_remove_writeuppage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
    ]
