# Generated by Django 5.2.3 on 2025-06-15 14:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_intro_text_remove_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutmepage',
            name='highlights',
            field=wagtail.fields.StreamField([('certificate', 3), ('paragraph', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('link', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
