# Generated by Django 5.2.3 on 2025-06-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_writeupitempage_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeupitempage',
            name='rating',
            field=models.DecimalField(blank=True, choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], decimal_places=1, help_text='Optional rating between 1.0 and 5.0 (halves allowed)', max_digits=2, null=True),
        ),
    ]
