# Generated by Django 5.2.3 on 2025-06-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_writeupitempage_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeupitempage',
            options={'verbose_name': 'Writeup Item'},
        ),
        migrations.AddField(
            model_name='writeupitempage',
            name='author',
            field=models.CharField(blank=True, help_text='Name of the person who wrote this writeup', max_length=100),
        ),
    ]
