# Generated by Django 5.2.3 on 2025-07-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_writeupitempage_options_writeupitempage_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The actual quote.', verbose_name='Quote Text')),
                ('author', models.CharField(blank=True, help_text='The author of the quote (optional).', max_length=255, null=True, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.AddField(
            model_name='writeupitempage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional link to a YouTube video', null=True),
        ),
    ]
