apiVersion: v1
kind: PersistentVolume
metadata:
  name: wagtail-staticfiles-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /home/kick/valknode/wagtail-src/staticfiles
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - debian
