# Generated by Django 5.2.7 on 2025-10-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_privacypolicypage'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivacyPolicyPage',
            new_name='GeneralPage',
        ),
    ]
