# Generated by Django 5.2.7 on 2025-11-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpage_author_customuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text="User's role or title (e.g. CEO, Developer, etc.)", max_length=100),
        ),
    ]
