# Generated by Django 5.2.7 on 2025-11-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_customuserprofile_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.DeleteModel(
            name='CustomUserProfile',
        ),
    ]
