apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:9.1.3
        ports:
        - containerPort: 5601
          name: http
        env:
        - name: ELASTICSEARCH_SERVICE_TOKEN
          value: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpkVXlfdEJBMlMyYWo5aXN1ckpFdW5R"
        # - name: ELASTICSEARCH_SERVICE_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: kibana-token
        #       key: service-token
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        - name: es-certs
          mountPath: /usr/share/kibana/config/certs
          readOnly: true
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
      - name: es-certs
        secret:
          secretName: es-certs
