apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"

    # ingress is already handling TLS
    server.ssl.enabled: false
    
    elasticsearch.hosts: ["https://elasticsearch:9200"]

    elasticsearch.ssl.certificateAuthorities: [ "/usr/share/kibana/config/certs/ca.crt" ]

    elasticsearch.serviceAccountToken: ${ELASTICSEARCH_SERVICE_TOKEN}
    #elasticsearch.ssl.verificationMode: full

    xpack.encryptedSavedObjects.encryptionKey: c4dc79cec498fbf900819cd4da2e66e7
    xpack.reporting.encryptionKey: aff00a79bbb5e99ecd19a2e9298cc711
    xpack.security.encryptionKey: 32f6f8e4a5b4c3d2e1f0a9b8c7d6e5f4