apiVersion: apps/v1
kind: Deployment
metadata:
  name: beats
spec:
  selector:
    matchLabels:
      app: beats
  replicas: 1
  template:
    metadata:
      labels:
        app: beats
    spec:
      containers:
      - name: beats
        image: elastic/heartbeat:9.0.3
        ports:
        - containerPort: 80
